version: '3.8'

services:
  l484-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: l484-innovation-platform
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# No external networks needed for basic deployment