version: '3.8'

services:
  l484-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: syntropy
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production