version: '3.8'

services:
  l484-app:
    image: ghcr.io/tx1138/gabe:latest
    container_name: l484-innovation-platform
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# No networks needed for simple deployment