name: Deploy to Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          # Create backup of current deployment
          if [ -d "/var/www/html_backup" ]; then
            rm -rf /var/www/html_backup
          fi
          if [ -d "/var/www/html" ]; then
            mv /var/www/html /var/www/html_backup
          fi
          
          # Create new directory
          mkdir -p /var/www/html
          
          # Clone and build on server
          cd /tmp
          rm -rf proux
          git clone https://github.com/Zazawowow/proux.git
          cd proux
          
          # Install Node.js if not present
          if ! command -v node &> /dev/null; then
            curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
            apt-get install -y nodejs
          fi
          
          # Build project
          npm ci
          npm run build
          
          # Copy built files to web directory
          cp -r dist/* /var/www/html/
          
          # Set proper permissions
          chown -R www-data:www-data /var/www/html
          chmod -R 755 /var/www/html
          
          # Test nginx configuration and reload
          nginx -t && systemctl reload nginx
          
          # Cleanup
          cd /
          rm -rf /tmp/proux
