name: Deploy to Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Create backup and prepare server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          # Create backup of current deployment
          if [ -d "/var/www/html_backup" ]; then
            rm -rf /var/www/html_backup
          fi
          if [ -d "/var/www/html" ]; then
            mv /var/www/html /var/www/html_backup
          fi
          
          # Create new directory
          mkdir -p /var/www/html
          
    - name: Deploy files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "dist/*"
        target: "/var/www/html/"
        strip_components: 1
        
    - name: Set permissions and reload nginx
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          # Set proper permissions
          chown -R www-data:www-data /var/www/html
          find /var/www/html -type d -exec chmod 755 {} \;
          find /var/www/html -type f -exec chmod 644 {} \;
          
          # Test nginx configuration and reload
          nginx -t && systemctl reload nginx
